const DEFAULT_SETTINGS={dailyLimit:30,newLimit:15,ttsRate:0.78,showIPA:true,showKoreanPron:true,autoSpeak:false,autoMaster:false,theme:'system'};
const S={tab:'home',search:'',category:'전체',mode:'all',sort:'priority',current:0,answer:false,selected:null,studyMode:'review',sentenceIndex:0,sentenceReveal:false,sentenceChunks:false,clozeIndex:0,clozeReveal:false,paperSelected:null,paperSearch:'',paperFilter:null,paperStudy:null,readingPaper:null,passageReveal:{}};
const V=document.querySelector('#view');
const norm=s=>(s||'').toLowerCase().replace(/\s+/g,' ').trim();
window.WORDS=[...new Map((window.WORDS||[]).map(w=>[norm(w.term),w])).values()].map((w,i)=>({...w,_id:i,pronunciation:w.pronunciation||'',koreanPronunciation:w.koreanPronunciation||'',collocations:w.collocations||[],sourceType:w.sourceType||'학습 예문',paper:w.paper||'General literature'}));
const getJSON=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const progress=()=>getJSON('pv-progress',{});const saveProgress=p=>localStorage.setItem('pv-progress',JSON.stringify(p));
const fav=()=>getJSON('pv-fav',[]);const saveFav=f=>localStorage.setItem('pv-fav',JSON.stringify(f));
const settings=()=>({...DEFAULT_SETTINGS,...getJSON('pv-settings',{})});const saveSettings=s=>{localStorage.setItem('pv-settings',JSON.stringify(s));applyTheme();};
const difficult=()=>getJSON('pv-difficult',[]);const saveDifficult=d=>localStorage.setItem('pv-difficult',JSON.stringify(d));
const studyDays=()=>getJSON('pv-study-days',[]);
function recordStudyDay(){const d=new Date().toISOString().slice(0,10),a=studyDays();if(!a.includes(d)){a.push(d);localStorage.setItem('pv-study-days',JSON.stringify(a.slice(-365)))}}
function streak(){const a=new Set(studyDays());let n=0,d=new Date();for(;;){const k=d.toISOString().slice(0,10);if(a.has(k)){n++;d.setDate(d.getDate()-1)}else break}return n}
function applyTheme(){const t=settings().theme;document.documentElement.dataset.theme=t==='system'?'':t}applyTheme();
const cats=()=>['전체',...new Set(WORDS.map(w=>w.category))];const isMastered=w=>!!progress()[w.term]?.mastered;const masteredCount=()=>WORDS.filter(isMastered).length;
const weakScore=w=>{const r=progress()[w.term]||{};return (r.wrong||0)*3+(r.seen||0)-(r.correct||0)-(r.mastery||0)};
const weakWords=()=>WORDS.filter(w=>!isMastered(w)&&(progress()[w.term]?.wrong||0)>0).sort((a,b)=>weakScore(b)-weakScore(a));
function dueCount(){const p=progress(),now=Date.now();return WORDS.filter(w=>!p[w.term]?.mastered&&(!p[w.term]||(p[w.term].next&&p[w.term].next<=now))).length}
function paperWords(paper){if(!paper)return WORDS;const p=typeof paper==='string'?(PAPER_LIBRARY||[]).find(x=>x.id===paper):paper;if(!p)return WORDS;const f=(p.focus||[]).map(norm);return WORDS.filter(w=>{const hay=norm([w.term,w.korean,w.meaning,w.category,w.paper].join(' '));if(p.id==='jin2011')return /jin et al|detachment frequency|coalesc|macrolayer|bubble/.test(hay);if(p.id==='kim2007')return /kim et al|contact angle|wettability|wicking|roughness|nanoparticle/.test(hay);if(p.id==='surtaev2017')return /surtaev|capillary-porous|transient|film boiling|stepwise/.test(hay);if(p.id==='chfReview')return /critical heat flux|\bchf\b|hydrodynamic|dryout|wetting|boiling crisis/.test(hay);if(p.id==='ln2Visualization')return /bubble|nucleation|departure|visual|high-speed/.test(hay);if(p.id==='uncertainty')return /uncertainty|calibration|thermocouple|measurement|heat flux|accuracy|error/.test(hay);if(p.id==='surfaceSEM')return /surface|roughness|chemistry|morphology|coating|contact angle/.test(hay);return f.some(x=>hay.includes(x))})}
function activeUniverse(){return S.paperStudy?paperWords(S.paperStudy):WORDS}
function queue(){const set=settings(),p=progress(),now=Date.now(),active=activeUniverse().filter(w=>!p[w.term]?.mastered);const overdue=active.filter(w=>p[w.term]?.next&&p[w.term].next<=now).sort((a,b)=>(p[a.term].next||0)-(p[b.term].next||0));const weak=active.filter(w=>(p[w.term]?.wrong||0)>0&&!overdue.includes(w)).sort((a,b)=>weakScore(b)-weakScore(a));const fresh=active.filter(w=>!p[w.term]).slice(0,set.newLimit);const seen=new Set(),out=[];for(const w of [...overdue,...weak,...fresh]){if(!seen.has(w.term)){out.push(w);seen.add(w.term)}if(out.length>=set.dailyLimit)break}return out}
function speak(t){if(!t)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=settings().ttsRate;speechSynthesis.speak(u)}
function setTab(t){S.tab=t;S.selected=null;if(t!=='papers')S.paperSelected=null;document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));render();window.scrollTo({top:0,behavior:'smooth'})}
function startMode(m){S.studyMode=m;S.answer=false;S.sentenceReveal=false;S.sentenceChunks=false;S.clozeReveal=false;setTab('study')}
function openMode(m){S.mode=m;S.category='전체';S.paperFilter=null;setTab('words')}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function home(){const m=masteredCount(),pct=WORDS.length?m/WORDS.length*100:0,w=weakWords().length;const tiles=[['Boiling','💧'],['Heat Transfer','♨'],['Bubble Dynamics','◌'],['Surface','▱'],['Cryogenics','❄'],['Experiment','⌁'],['Data & Statistics','∑'],['Academic English','Aa']];return `<section class="card hero"><div class="row between"><div><div class="meta">오늘 학습 가능</div><div class="big">${Math.min(dueCount(),settings().dailyLimit)}개</div></div><div class="streak-box"><strong>${streak()}일</strong><small>연속 학습</small></div></div><div class="progress"><div style="width:${pct}%"></div></div><div class="stats-row"><span>전체 <b>${WORDS.length}</b></span><span>완전 암기 <b>${m}</b></span><span>약한 단어 <b>${w}</b></span></div><button class="btn primary wide" onclick="startMode('review')">단어 복습 시작</button><div class="action-grid"><button class="btn secondary" onclick="startMode('sentence')">문장 독해</button><button class="btn secondary" onclick="startMode('cloze')">빈칸 퀴즈</button></div></section><div class="section-title">독해를 빠르게 만드는 학습</div><div class="feature-grid"><button class="feature-card" onclick="startMode('sentence')"><b>문장 덩어리 읽기</b><span>절·연결어 기준으로 긴 문장을 끊어 읽고 번역을 나중에 확인</span></button><button class="feature-card" onclick="startMode('weak')"><b>약한 단어 집중</b><span>틀린 횟수와 복습 기록을 기준으로 자동 선별</span></button><button class="feature-card" onclick="setTab('papers')"><b>논문별 학습</b><span>논문마다 핵심 문장·연결 단어·진도를 묶어서 학습</span></button><button class="feature-card" onclick="openMode('mastered')"><b>암기 완료 보관함</b><span>완전히 외운 단어는 일반 복습에서 자동 제외</span></button></div><div class="section-title">카테고리</div><div class="grid">${tiles.map(([n,i])=>`<button class="tile" onclick="S.category='${n}';S.mode='all';S.paperFilter=null;setTab('words')"><div class="icon">${i}</div><strong>${n}</strong><small>${WORDS.filter(w=>w.category===n).length}개</small></button>`).join('')}</div>`}
function wordsView(){if(S.selected!==null)return detail(S.selected);const q=norm(S.search),p=progress(),f=fav(),base=S.paperFilter?paperWords(S.paperFilter):WORDS;let list=base.map(w=>({w,i:WORDS.indexOf(w)})).filter(({w})=>{const categoryOK=S.category==='전체'||w.category===S.category;const text=norm([w.term,w.korean,w.koreanPronunciation,w.meaning,w.example,w.translation,w.paper,...w.collocations].join(' '));const searchOK=!q||text.includes(q);const statusOK=S.mode==='all'||(S.mode==='fav'&&f.includes(w.term))||(S.mode==='mastered'&&p[w.term]?.mastered)||(S.mode==='weak'&&(p[w.term]?.wrong||0)>0&&!p[w.term]?.mastered);return categoryOK&&searchOK&&statusOK});if(S.sort==='alpha')list.sort((a,b)=>a.w.term.localeCompare(b.w.term));if(S.sort==='weak')list.sort((a,b)=>weakScore(b.w)-weakScore(a.w));if(S.sort==='priority')list.sort((a,b)=>(a.w.priority||3)-(b.w.priority||3)||a.w.term.localeCompare(b.w.term));const paperTitle=S.paperFilter?(PAPER_LIBRARY.find(x=>x.id===S.paperFilter)?.title||'논문 필터'):'';return `${paperTitle?`<div class="filter-banner"><span>논문 필터: ${escapeHtml(paperTitle)}</span><button onclick="S.paperFilter=null;render()">해제</button></div>`:''}<div class="search-row"><input class="search" placeholder="단어·뜻·예문·논문 검색" value="${escapeHtml(S.search)}" oninput="S.search=this.value;render()"><select onchange="S.sort=this.value;render()"><option value="priority" ${S.sort==='priority'?'selected':''}>추천순</option><option value="alpha" ${S.sort==='alpha'?'selected':''}>ABC순</option><option value="weak" ${S.sort==='weak'?'selected':''}>약한순</option></select></div><div class="status-tabs"><button class="${S.mode==='all'?'active':''}" onclick="S.mode='all';render()">전체</button><button class="${S.mode==='weak'?'active':''}" onclick="S.mode='weak';render()">△ 약한 단어</button><button class="${S.mode==='fav'?'active':''}" onclick="S.mode='fav';render()">★ 즐겨찾기</button><button class="${S.mode==='mastered'?'active':''}" onclick="S.mode='mastered';render()">✓ 암기 완료</button></div><div class="chips">${cats().map(c=>`<button class="chip ${c===S.category?'active':''}" onclick="S.category='${escapeHtml(c)}';render()">${escapeHtml(c)}</button>`).join('')}</div><div class="list-count">${list.length}개 단어</div><div>${list.map(({w,i})=>wordCard(w,i,p,f)).join('')||'<div class="empty card">조건에 맞는 단어가 없습니다.</div>'}</div>`}
function wordCard(w,i,p,f){const r=p[w.term]||{};return `<button class="word-card" onclick="openWord(${i})"><div class="row between"><strong>${escapeHtml(w.term)}</strong><span class="icons">${r.mastered?'✓ ':''}${f.includes(w.term)?'★':''}</span></div><div class="pron-line">${settings().showIPA&&w.pronunciation?`<span>${escapeHtml(w.pronunciation)}</span>`:''}${settings().showKoreanPron&&w.koreanPronunciation?`<span class="ko-pron">[${escapeHtml(w.koreanPronunciation)}]</span>`:''}</div><div class="meaning-line">${escapeHtml(w.korean)}</div><div class="row between"><span class="meta">${escapeHtml(w.category)}</span><span class="source-mini">${escapeHtml(w.sourceType)}</span></div>${r.seen?`<div class="tiny-stat">복습 ${r.seen} · 어려움 ${r.wrong||0}</div>`:''}</button>`}
function openWord(i){S.selected=i;render();window.scrollTo({top:0,behavior:'smooth'});if(settings().autoSpeak)speak(WORDS[i].term)}
function detail(i){const w=WORDS[i],f=fav().includes(w.term),r=progress()[w.term]||{},done=!!r.mastered;return `<div class="detail"><button class="back" onclick="S.selected=null;render()">← 단어장</button><div class="card detail-card"><div class="row between top-align"><div><h2>${escapeHtml(w.term)}</h2>${settings().showIPA&&w.pronunciation?`<div class="pron">${escapeHtml(w.pronunciation)}</div>`:''}${settings().showKoreanPron&&w.koreanPronunciation?`<div class="ko-pron big-pron">[${escapeHtml(w.koreanPronunciation)}]</div>`:''}</div><button class="icon-btn" onclick="toggleFav(${i})">${f?'★':'☆'}</button></div><button class="btn outline" onclick="speak(${JSON.stringify(w.term)})">🔊 발음 듣기</button><div class="block"><h3>뜻</h3><div class="definition">${escapeHtml(w.korean)}</div><p>${escapeHtml(w.meaning)}</p></div>${w.collocations.length?`<div class="block"><h3>자주 같이 쓰는 표현</h3>${w.collocations.map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('')}</div>`:''}<div class="block example-block"><div class="row between"><h3>예문</h3><span class="source-badge ${w.sourceType==='논문 원문'?'quote':''}">${escapeHtml(w.sourceType)}</span></div><p class="example">${escapeHtml(w.example)}</p><button class="btn outline small" onclick="speak(${JSON.stringify(w.example)})">🔊 예문 듣기</button><p class="translation">${escapeHtml(w.translation)}</p><div class="paper-source">출처/연결: ${escapeHtml(w.paper)}</div></div><div class="mini-stats"><span>복습 ${r.seen||0}</span><span>어려움 ${r.wrong||0}</span><span>정답 ${r.correct||0}</span></div><button class="btn secondary wide" onclick="readThisExample(${i})">이 예문으로 독해 연습</button><button class="btn ${done?'secondary':'master'} wide" onclick="toggleMastered(${i})">${done?'↩ 복습에 다시 포함':'✓ 완전 암기 완료'}</button>${done?'<p class="master-note">이 단어는 일반 복습 큐에서 제외되어 있습니다.</p>':''}</div></div>`}
function toggleFav(i){const t=WORDS[i].term;let f=fav();f=f.includes(t)?f.filter(x=>x!==t):[...f,t];saveFav(f);render()}
function toggleMastered(i){const w=WORDS[i],p=progress(),old=p[w.term]||{mastery:0,seen:0,wrong:0,correct:0};p[w.term]=old.mastered?{...old,mastered:false,next:Date.now()}:{...old,mastered:true,next:null,masteredAt:Date.now()};saveProgress(p);recordStudyDay();render()}
function readThisExample(i){S.readingPaper=null;S._customSentence={text:WORDS[i].example,translation:WORDS[i].translation,source:WORDS[i].paper,term:WORDS[i].term};S.studyMode='sentence';S.sentenceIndex=0;S.sentenceReveal=false;S.sentenceChunks=false;setTab('study')}
function studyTabs(){return `<div class="study-tabs"><button class="${S.studyMode==='review'?'active':''}" onclick="S.studyMode='review';S.answer=false;render()">단어 복습</button><button class="${S.studyMode==='sentence'?'active':''}" onclick="S.studyMode='sentence';S.sentenceReveal=false;render()">문장 독해</button><button class="${S.studyMode==='cloze'?'active':''}" onclick="S.studyMode='cloze';S.clozeReveal=false;render()">빈칸</button><button class="${S.studyMode==='weak'?'active':''}" onclick="S.studyMode='weak';render()">약한 단어</button></div>`}
function study(){return studyTabs()+(S.studyMode==='review'?reviewStudy():S.studyMode==='sentence'?sentenceStudy():S.studyMode==='cloze'?clozeStudy():weakStudy())}
function reviewStudy(){const a=queue();if(!a.length)return `<div class="empty card"><div class="done-icon">✓</div><h2>복습 큐 완료</h2><p>현재 복습할 단어가 없습니다.</p>${S.paperStudy?'<button class="btn secondary" onclick="S.paperStudy=null;render()">논문 필터 해제</button>':''}</div>`;S.current=Math.min(S.current,a.length-1);const w=a[S.current],idx=WORDS.indexOf(w);return `${S.paperStudy?`<div class="filter-banner"><span>논문 전용 복습</span><button onclick="S.paperStudy=null;S.current=0;render()">해제</button></div>`:''}<div class="study-head"><span>${S.current+1}/${a.length}</span><span>${escapeHtml(w.category)}</span></div><div class="progress"><div style="width:${(S.current+1)/a.length*100}%"></div></div><div class="card study-card" onclick="S.answer=true;render()"><span class="study-label">단어</span><h2>${escapeHtml(w.term)}</h2>${settings().showIPA&&w.pronunciation?`<div class="pron">${escapeHtml(w.pronunciation)}</div>`:''}${settings().showKoreanPron&&w.koreanPronunciation?`<div class="ko-pron big-pron">[${escapeHtml(w.koreanPronunciation)}]</div>`:''}${S.answer?`<div class="answer"><h3>${escapeHtml(w.korean)}</h3><p>${escapeHtml(w.meaning)}</p><div class="example-mini">${escapeHtml(w.example)}</div><div class="translation">${escapeHtml(w.translation)}</div></div>`:'<div class="tap-hint">카드를 탭하면 답이 표시됩니다</div>'}</div>${S.answer?`<div class="review-grid"><button onclick="grade(0)">다시<small>10분</small></button><button onclick="grade(1)">어려움<small>1일</small></button><button onclick="grade(2)">보통<small>간격 증가</small></button><button onclick="grade(3)">쉬움<small>큰 간격</small></button></div><button class="btn master wide" onclick="masterFromStudy(${idx})">✓ 완전 암기</button>`:`<button class="btn primary wide" onclick="S.answer=true;render()">정답 보기</button>`}`}
function updateReview(w,q){const p=progress(),o=p[w.term]||{mastery:0,seen:0,wrong:0,correct:0},day=86400000;let m=o.mastery||0,n={...o,mastered:false,seen:(o.seen||0)+1,lastQuality:q,lastSeen:Date.now()};if(q<=1)n.wrong=(o.wrong||0)+1;else n.correct=(o.correct||0)+1;if(q===0){n.mastery=Math.max(0,m-1);n.next=Date.now()+600000}if(q===1){n.mastery=Math.max(1,m);n.next=Date.now()+day}if(q===2){m=Math.min(5,m+1);n.mastery=m;n.next=Date.now()+[1,3,7,14,30,60][m]*day}if(q===3){m=Math.min(5,m+2);n.mastery=m;n.next=Date.now()+[3,7,14,30,60,90][m]*day;if(settings().autoMaster&&m>=5){n.mastered=true;n.next=null;n.masteredAt=Date.now()}}p[w.term]=n;saveProgress(p);recordStudyDay()}
function grade(q){const a=queue();if(!a.length)return;updateReview(a[S.current],q);S.answer=false;S.current=Math.min(S.current,Math.max(0,queue().length-1));render()}
function masterFromStudy(i){const w=WORDS[i],p=progress(),o=p[w.term]||{mastery:0,seen:0};p[w.term]={...o,mastered:true,next:null,masteredAt:Date.now(),seen:(o.seen||0)+1,correct:(o.correct||0)+1};saveProgress(p);recordStudyDay();S.answer=false;S.current=Math.min(S.current,Math.max(0,queue().length-1));render()}
function sentencePool(){if(S._customSentence){const x=S._customSentence;S._customSentence=null;return [x]}let arr=[];const papers=S.readingPaper?(PAPER_LIBRARY||[]).filter(p=>p.id===S.readingPaper):(PAPER_LIBRARY||[]);for(const p of papers)for(const q of (p.passages||[]))arr.push({text:q.text,translation:q.translation,source:p.title,paperId:p.id,sourceType:'논문 원문'});const ws=S.readingPaper?paperWords(S.readingPaper):WORDS.filter(w=>w.example&&w.translation);for(const w of ws.slice(0,250))arr.push({text:w.example,translation:w.translation,source:w.paper,term:w.term,sourceType:w.sourceType});return arr}
function chunkSentence(text){const markers=/(\bwhich\b|\bthat\b|\bwhereas\b|\bwhile\b|\bbecause\b|\balthough\b|\bhowever\b|\btherefore\b|\bdue to\b|\bin order to\b|\bas a function of\b)/ig;return text.replace(/;/g,';|').replace(/,\s+/g,',| ').replace(markers,'|$1').split('|').map(x=>x.trim()).filter(Boolean)}
function toggleDifficult(text){let d=difficult();d=d.includes(text)?d.filter(x=>x!==text):[...d,text];saveDifficult(d);render()}
function sentenceStudy(){const a=sentencePool();if(!a.length)return '<div class="empty card">독해 문장이 없습니다.</div>';S.sentenceIndex=((S.sentenceIndex%a.length)+a.length)%a.length;const x=a[S.sentenceIndex],saved=difficult().includes(x.text),chunks=chunkSentence(x.text);return `${S.readingPaper?`<div class="filter-banner"><span>선택 논문 문장만</span><button onclick="S.readingPaper=null;S.sentenceIndex=0;render()">해제</button></div>`:''}<div class="study-head"><span>문장 ${S.sentenceIndex+1}/${a.length}</span><span>${escapeHtml(x.sourceType||'학습 예문')}</span></div><div class="card reading-card"><div class="row between"><span class="study-label">독해 훈련</span><button class="icon-btn" onclick="toggleDifficult(${JSON.stringify(x.text)})">${saved?'★':'☆'}</button></div>${S.sentenceChunks?`<div class="chunks">${chunks.map((c,i)=>`<div><b>${i+1}</b><span>${escapeHtml(c)}</span></div>`).join('')}</div>`:`<p class="reading-sentence">${escapeHtml(x.text)}</p>`}<div class="reading-tools"><button class="btn outline small" onclick="speak(${JSON.stringify(x.text)})">🔊 듣기</button><button class="btn outline small" onclick="S.sentenceChunks=!S.sentenceChunks;render()">${S.sentenceChunks?'원문 보기':'끊어읽기'}</button></div>${S.sentenceReveal?`<div class="answer translation-box">${escapeHtml(x.translation)}</div>`:'<button class="btn primary wide" onclick="S.sentenceReveal=true;render()">해석 확인</button>'}<div class="paper-source">${escapeHtml(x.source||'')}</div></div><div class="nav-pair"><button class="btn secondary" onclick="S.sentenceIndex--;S.sentenceReveal=false;S.sentenceChunks=false;render()">← 이전</button><button class="btn secondary" onclick="S.sentenceIndex++;S.sentenceReveal=false;S.sentenceChunks=false;render()">다음 →</button></div><div class="tip card"><b>독해 순서</b><span>① 핵심 동사 찾기 → ② 연결어·관계절 경계 찾기 → ③ 전공 명사구 묶기 → ④ 마지막에 번역 확인</span></div>`}
function clozeItems(){let a=(S.paperStudy?paperWords(S.paperStudy):WORDS).filter(w=>!isMastered(w)&&w.example&&norm(w.example).includes(norm(w.term)));return a.length?a:WORDS.filter(w=>!isMastered(w)&&w.example).slice(0,100)}
function blankTerm(text,term){const escaped=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return text.replace(new RegExp(escaped,'ig'),'________')}
function clozeStudy(){const a=clozeItems();if(!a.length)return '<div class="empty card">빈칸 문제를 만들 수 있는 단어가 없습니다.</div>';S.clozeIndex=((S.clozeIndex%a.length)+a.length)%a.length;const w=a[S.clozeIndex],q=blankTerm(w.example,w.term);return `<div class="study-head"><span>빈칸 ${S.clozeIndex+1}/${a.length}</span><span>${escapeHtml(w.category)}</span></div><div class="card cloze-card"><span class="study-label">문맥으로 단어 맞히기</span><p class="reading-sentence">${escapeHtml(q)}</p><div class="hint">힌트: ${escapeHtml(w.korean)}</div>${S.clozeReveal?`<div class="answer"><h2>${escapeHtml(w.term)}</h2>${settings().showKoreanPron&&w.koreanPronunciation?`<div class="ko-pron">[${escapeHtml(w.koreanPronunciation)}]</div>`:''}<p>${escapeHtml(w.translation)}</p></div>`:'<button class="btn primary wide" onclick="S.clozeReveal=true;render()">정답 보기</button>'}</div>${S.clozeReveal?`<div class="action-grid"><button class="btn danger" onclick="clozeGrade(0)">몰랐음</button><button class="btn success" onclick="clozeGrade(2)">알았음</button></div>`:''}`}
function clozeGrade(q){const a=clozeItems();if(!a.length)return;updateReview(a[S.clozeIndex],q);S.clozeReveal=false;S.clozeIndex=Math.min(S.clozeIndex,Math.max(0,clozeItems().length-1));render()}
function weakStudy(){const a=weakWords();if(!a.length)return '<div class="empty card"><div class="done-icon">✓</div><h2>약한 단어 없음</h2><p>아직 어려움으로 누적된 단어가 없습니다.</p></div>';return `<div class="section-title">틀린 기록 기반 약한 단어</div>${a.slice(0,40).map(w=>{const i=WORDS.indexOf(w),r=progress()[w.term]||{};return `<button class="weak-card" onclick="openWeak(${i})"><div><strong>${escapeHtml(w.term)}</strong><span>${escapeHtml(w.korean)}</span></div><div><b>${r.wrong||0}</b><small>어려움</small></div></button>`}).join('')}`}
function openWeak(i){S.studyMode='review';S.paperStudy=null;const p=progress(),w=WORDS[i],r=p[w.term]||{};p[w.term]={...r,mastered:false,next:Date.now()-1};saveProgress(p);S.current=0;render()}
function papers(){if(S.paperSelected)return paperDetail(S.paperSelected);const q=norm(S.paperSearch);const list=(PAPER_LIBRARY||[]).filter(p=>!q||norm([p.title,p.authors,p.journal,p.file,...p.focus].join(' ')).includes(q));return `<input class="search" placeholder="논문 제목·저자·주제 검색" value="${escapeHtml(S.paperSearch)}" oninput="S.paperSearch=this.value;render()"><div class="paper-intro card"><b>논문별 학습 허브</b><span>핵심 문장, 연결 어휘, 암기 진도를 논문 단위로 묶었습니다.</span></div><div class="paper-list">${list.map(p=>{const ws=paperWords(p),done=ws.filter(isMastered).length,pc=ws.length?Math.round(done/ws.length*100):0;return `<button class="paper-card card" onclick="S.paperSelected='${p.id}';render()"><div class="paper-title">${escapeHtml(p.title)}</div><div class="paper-authors">${escapeHtml(p.authors)}</div><div class="meta">${escapeHtml(p.journal)} · ${escapeHtml(p.file)}</div><div class="tag-row">${p.focus.map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('')}</div><div class="progress small-progress"><div style="width:${pc}%"></div></div><div class="row between meta"><span>연결 단어 ${ws.length}</span><span>암기 ${done} · ${pc}%</span></div></button>`}).join('')}</div>`}
function togglePassage(key){S.passageReveal[key]=!S.passageReveal[key];render()}
function paperDetail(id){const p=(PAPER_LIBRARY||[]).find(x=>x.id===id);if(!p)return '<div class="empty">논문 정보가 없습니다.</div>';const ws=paperWords(p),done=ws.filter(isMastered).length;return `<button class="back" onclick="S.paperSelected=null;render()">← 논문 목록</button><div class="card paper-detail"><div class="eyebrow">PAPER STUDY</div><h2>${escapeHtml(p.title)}</h2><div class="paper-authors">${escapeHtml(p.authors)}</div><div class="meta">${escapeHtml(p.journal)} · 보유 파일: ${escapeHtml(p.file)}</div><div class="tag-row">${p.focus.map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('')}</div><div class="paper-stat-grid"><div><b>${ws.length}</b><span>연결 단어</span></div><div><b>${done}</b><span>암기 완료</span></div><div><b>${p.passages.length}</b><span>원문 문장</span></div></div><div class="action-grid"><button class="btn primary" onclick="studyPaper('${p.id}')">이 논문 단어 학습</button><button class="btn secondary" onclick="showPaperWords('${p.id}')">연결 단어 보기</button></div><button class="btn secondary wide" onclick="readPaper('${p.id}')">핵심 문장 독해 훈련</button></div><div class="section-title">핵심 원문 문장</div>${p.passages.map((x,i)=>{const k=`${p.id}:${i}`,show=!!S.passageReveal[k];return `<div class="card passage-card"><p>${escapeHtml(x.text)}</p><div class="reading-tools"><button class="btn outline small" onclick="speak(${JSON.stringify(x.text)})">🔊 듣기</button><button class="btn outline small" onclick="togglePassage('${k}')">${show?'해석 숨기기':'해석 보기'}</button></div>${show?`<div class="translation-box">${escapeHtml(x.translation)}</div>`:''}</div>`}).join('')}<div class="section-title">연결 단어 미리보기</div><div>${ws.slice(0,12).map(w=>wordCard(w,WORDS.indexOf(w),progress(),fav())).join('')}</div>`}
function studyPaper(id){S.paperStudy=id;S.studyMode='review';S.current=0;S.answer=false;setTab('study')}function showPaperWords(id){S.paperFilter=id;S.mode='all';S.category='전체';setTab('words')}function readPaper(id){S.readingPaper=id;S.studyMode='sentence';S.sentenceIndex=0;S.sentenceReveal=false;S.sentenceChunks=false;setTab('study')}
function settingsView(){const s=settings(),p=progress();const bytes=new Blob([localStorage.getItem('pv-progress')||'',localStorage.getItem('pv-fav')||'']).size;return `<div class="card settings-card"><h2>학습 설정</h2><label class="setting-control"><span><b>하루 복습량</b><small>복습 큐의 최대 카드 수</small></span><select onchange="setSetting('dailyLimit',+this.value)">${[10,20,30,50,80,100].map(v=>`<option ${s.dailyLimit===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="setting-control"><span><b>하루 새 단어</b><small>새 단어가 한꺼번에 너무 많이 섞이지 않게 제한</small></span><select onchange="setSetting('newLimit',+this.value)">${[5,10,15,20,30,50].map(v=>`<option ${s.newLimit===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="setting-control column"><span><b>TTS 발음 속도</b><small>${s.ttsRate.toFixed(2)}×</small></span><input type="range" min="0.5" max="1.1" step="0.05" value="${s.ttsRate}" oninput="setSetting('ttsRate',+this.value,false);this.previousElementSibling.querySelector('small').textContent=(+this.value).toFixed(2)+'×'"></label>${toggleSetting('showIPA','IPA 발음기호 표시','단어와 학습 카드에서 IPA 표시',s.showIPA)}${toggleSetting('showKoreanPron','한글 발음 표시','IPA 아래에 한글식 발음 표시',s.showKoreanPron)}${toggleSetting('autoSpeak','단어 열 때 자동 발음','상세 화면 진입 시 TTS 자동 재생',s.autoSpeak)}${toggleSetting('autoMaster','쉬움 반복 시 자동 암기 완료','숙련도 최고 단계에서 복습 큐 자동 제외',s.autoMaster)}<label class="setting-control"><span><b>화면 테마</b><small>시스템·다크·라이트</small></span><select onchange="setSetting('theme',this.value)"><option value="system" ${s.theme==='system'?'selected':''}>시스템</option><option value="dark" ${s.theme==='dark'?'selected':''}>다크</option><option value="light" ${s.theme==='light'?'selected':''}>라이트</option></select></label></div><div class="card settings-card"><h2>데이터 관리</h2><div class="data-summary"><span>단어 <b>${WORDS.length}</b></span><span>학습 기록 <b>${Object.keys(p).length}</b></span><span>암기 완료 <b>${masteredCount()}</b></span><span>로컬 데이터 <b>${Math.max(1,Math.round(bytes/1024))} KB</b></span></div><div class="action-grid"><button class="btn secondary" onclick="exportBackup()">백업 내보내기</button><button class="btn secondary" onclick="document.querySelector('#backupImport').click()">백업 가져오기</button></div><button class="btn secondary wide" onclick="refreshApp()">앱 캐시 새로고침</button><button class="btn danger wide" onclick="resetStudy()">학습 기록만 초기화</button><button class="btn danger-outline wide" onclick="resetAll()">모든 개인 데이터 초기화</button></div><div class="card settings-card"><h2>독해 학습 원칙</h2><ol class="reading-rules"><li>문장을 처음부터 번역하지 말고 <b>주어·핵심동사</b>를 먼저 찾기</li><li>which, that, whereas, due to 같은 <b>연결어 경계</b>에서 끊기</li><li>critical heat flux처럼 <b>전공 명사구는 하나의 덩어리</b>로 읽기</li><li>문장 뜻을 먼저 추론한 뒤 한국어 해석으로 검증하기</li><li>완전히 외운 단어는 복습에서 제외하고 어려운 단어에 시간을 집중하기</li></ol></div>`}
function toggleSetting(key,title,desc,val){return `<label class="setting-control"><span><b>${title}</b><small>${desc}</small></span><input type="checkbox" ${val?'checked':''} onchange="setSetting('${key}',this.checked)"></label>`}
function setSetting(k,v,rerender=true){const s=settings();s[k]=v;saveSettings(s);if(rerender)render()}
function exportBackup(){const data={version:2,exportedAt:new Date().toISOString(),progress:progress(),favorites:fav(),settings:settings(),difficult:difficult(),studyDays:studyDays()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PaperVocab_backup_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importBackup(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.progress)localStorage.setItem('pv-progress',JSON.stringify(d.progress));if(d.favorites)localStorage.setItem('pv-fav',JSON.stringify(d.favorites));if(d.settings)localStorage.setItem('pv-settings',JSON.stringify({...DEFAULT_SETTINGS,...d.settings}));if(d.difficult)localStorage.setItem('pv-difficult',JSON.stringify(d.difficult));if(d.studyDays)localStorage.setItem('pv-study-days',JSON.stringify(d.studyDays));applyTheme();alert('백업을 불러왔습니다.');render()}catch{alert('올바른 PaperVocab 백업 파일이 아닙니다.')}};r.readAsText(file)}
async function refreshApp(){if('caches'in window){for(const k of await caches.keys())await caches.delete(k)}if('serviceWorker'in navigator){const r=await navigator.serviceWorker.getRegistrations();for(const x of r)await x.update()}location.reload()}
function resetStudy(){if(confirm('복습 기록과 암기 완료 상태를 초기화할까요? 즐겨찾기와 설정은 유지됩니다.')){localStorage.removeItem('pv-progress');localStorage.removeItem('pv-study-days');render()}}
function resetAll(){if(confirm('즐겨찾기, 복습 기록, 설정, 저장 문장을 모두 삭제할까요?')){['pv-progress','pv-study-days','pv-fav','pv-settings','pv-difficult'].forEach(k=>localStorage.removeItem(k));applyTheme();render()}}
function render(){V.innerHTML=S.tab==='home'?home():S.tab==='words'?wordsView():S.tab==='study'?study():S.tab==='papers'?papers():settingsView()}
document.querySelectorAll('.tabbar button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelector('#backupImport')?.addEventListener('change',e=>{importBackup(e.target.files?.[0]);e.target.value=''});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');