const S={tab:'home',search:'',category:'전체',mode:'all',current:0,answer:false,selected:null};
const V=document.querySelector('#view');
const progress=()=>JSON.parse(localStorage.getItem('pv-progress')||'{}');
const save=p=>localStorage.setItem('pv-progress',JSON.stringify(p));
const fav=()=>JSON.parse(localStorage.getItem('pv-fav')||'[]');
const saveFav=f=>localStorage.setItem('pv-fav',JSON.stringify(f));
const cats=()=>['전체',...new Set(WORDS.map(w=>w.category))];
const isMastered=w=>!!progress()[w.term]?.mastered;
const masteredCount=()=>WORDS.filter(isMastered).length;
function queue(){const p=progress(),now=Date.now();const active=WORDS.filter(w=>!p[w.term]?.mastered);const overdue=active.filter(w=>p[w.term]&&p[w.term].next&&p[w.term].next<=now);const fresh=active.filter(w=>!p[w.term]);return [...overdue,...fresh].slice(0,30)}
function dueCount(){const p=progress(),now=Date.now();return WORDS.filter(w=>!p[w.term]?.mastered&&(!p[w.term]||(p[w.term].next&&p[w.term].next<=now))).length}
function speak(t){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.78;speechSynthesis.speak(u)}
function setTab(t){S.tab=t;S.selected=null;document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));render();window.scrollTo({top:0,behavior:'smooth'})}
function openMode(m){S.mode=m;S.category='전체';setTab('words')}
function home(){const d=dueCount(),m=masteredCount(),pct=WORDS.length?m/WORDS.length*100:0;const tiles=[['Boiling','💧'],['Heat Transfer','♨'],['Bubble Dynamics','◌'],['Surface','▱'],['Experiment','⌁'],['Academic English','Aa']];return `<section class="card hero"><div class="row between"><div><div class="meta">오늘 학습 가능</div><div class="big">${Math.min(d,30)}개</div></div><div class="hero-icon">◷</div></div><div class="progress"><div style="width:${pct}%"></div></div><div class="row between"><div class="meta">전체 ${WORDS.length}개</div><div class="meta">완전 암기 ${m}개</div></div><button class="btn primary wide" onclick="setTab('study')">학습 시작</button><button class="btn secondary wide" onclick="openMode('mastered')">✓ 암기 완료 단어 모아보기</button></section><div class="section-title">카테고리</div><div class="grid">${tiles.map(([n,i])=>`<button class="tile" onclick="S.category='${n}';S.mode='all';setTab('words')"><div class="icon">${i}</div><strong>${n}</strong><small>${WORDS.filter(w=>w.category===n).length}개</small></button>`).join('')}</div>`}
function wordsView(){if(S.selected!==null)return detail(S.selected);const q=S.search.trim().toLowerCase(),p=progress(),f=fav();let list=WORDS.map((w,i)=>({w,i})).filter(({w})=>{const categoryOK=S.category==='전체'||w.category===S.category;const text=[w.term,w.korean,w.koreanPronunciation,w.meaning,...w.collocations].join(' ').toLowerCase();const searchOK=!q||text.includes(q);const statusOK=S.mode==='all'||(S.mode==='fav'&&f.includes(w.term))||(S.mode==='mastered'&&p[w.term]?.mastered);return categoryOK&&searchOK&&statusOK});return `<input class="search" placeholder="단어, 뜻, 한글 발음, 예문 검색" value="${S.search}" oninput="S.search=this.value;render()"><div class="status-tabs"><button class="${S.mode==='all'?'active':''}" onclick="S.mode='all';render()">전체</button><button class="${S.mode==='fav'?'active':''}" onclick="S.mode='fav';render()">★ 즐겨찾기</button><button class="${S.mode==='mastered'?'active':''}" onclick="S.mode='mastered';render()">✓ 암기 완료</button></div><div class="chips">${cats().map(c=>`<button class="chip ${c===S.category?'active':''}" onclick="S.category='${c}';render()">${c}</button>`).join('')}</div><div class="list-count">${list.length}개 단어</div><div>${list.map(({w,i})=>wordCard(w,i,p,f)).join('')||'<div class="empty card">조건에 맞는 단어가 없습니다.</div>'}</div>`}
function wordCard(w,i,p,f){return `<button class="word-card" onclick="openWord(${i})"><div class="row between"><strong>${w.term}</strong><span class="icons">${p[w.term]?.mastered?'✓ ':''}${f.includes(w.term)?'★':''}</span></div><div class="pron-line"><span>${w.pronunciation}</span><span class="ko-pron">${w.koreanPronunciation}</span></div><div class="meaning-line">${w.korean}</div><div class="row between"><span class="meta">${w.category}</span><span class="source-mini">${w.sourceType||'학습 예문'}</span></div></button>`}
function openWord(i){S.selected=i;render();window.scrollTo({top:0,behavior:'smooth'})}
function detail(i){const w=WORDS[i],f=fav().includes(w.term),p=progress(),done=!!p[w.term]?.mastered;return `<div class="detail"><button class="back" onclick="S.selected=null;render()">← 단어장</button><div class="card detail-card"><div class="row between top-align"><div><h2>${w.term}</h2><div class="pron">${w.pronunciation}</div><div class="ko-pron big-pron">[${w.koreanPronunciation}]</div></div><button class="icon-btn" onclick="toggleFav(${i})">${f?'★':'☆'}</button></div><button class="btn outline" onclick="speak(${JSON.stringify(w.term)})">🔊 발음 듣기</button><div class="block"><h3>뜻</h3><div class="definition">${w.korean}</div><p>${w.meaning}</p></div><div class="block"><h3>자주 같이 쓰는 표현</h3>${w.collocations.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="block example-block"><div class="row between"><h3>예문</h3><span class="source-badge ${w.sourceType==='논문 원문'?'quote':''}">${w.sourceType||'학습 예문'}</span></div><p class="example">${w.example}</p><button class="btn outline small" onclick="speak(${JSON.stringify(w.example)})">🔊 예문 듣기</button><p class="translation">${w.translation}</p><div class="paper-source">출처/연결: ${w.paper}</div></div><button class="btn ${done?'secondary':'master'} wide" onclick="toggleMastered(${i})">${done?'↩ 복습에 다시 포함':'✓ 완전 암기 완료'}</button>${done?'<p class="master-note">이 단어는 복습 큐에서 제외되어 있습니다.</p>':''}</div></div>`}
function toggleFav(i){const t=WORDS[i].term;let f=fav();f=f.includes(t)?f.filter(x=>x!==t):[...f,t];saveFav(f);render()}
function toggleMastered(i){const w=WORDS[i],p=progress(),old=p[w.term]||{mastery:0};if(old.mastered){p[w.term]={...old,mastered:false,next:Date.now()}}else{p[w.term]={...old,mastered:true,next:null,masteredAt:Date.now()}}save(p);render()}
function study(){const a=queue();if(!a.length)return `<div class="empty card"><div class="done-icon">✓</div><h2>오늘 복습 완료</h2><p>복습 시점이 된 단어가 없습니다.</p><button class="btn secondary" onclick="openMode('mastered')">암기 완료 단어 보기</button></div>`;S.current=Math.min(S.current,a.length-1);const w=a[S.current],idx=WORDS.indexOf(w);return `<div class="study-head"><span>오늘 복습 ${S.current+1}/${a.length}</span><span>${w.category}</span></div><div class="progress"><div style="width:${(S.current+1)/a.length*100}%"></div></div><div class="card study-card" onclick="S.answer=true;render()"><span class="study-label">단어</span><h2>${w.term}</h2><div class="pron">${w.pronunciation}</div><div class="ko-pron big-pron">[${w.koreanPronunciation}]</div>${S.answer?`<div class="answer"><h3>${w.korean}</h3><p>${w.meaning}</p><div class="example-mini">${w.example}</div><div class="translation">${w.translation}</div></div>`:'<div class="tap-hint">카드를 탭하면 답이 표시됩니다</div>'}</div>${S.answer?`<div class="review-grid"><button onclick="grade(0)">다시<small>10분 후</small></button><button onclick="grade(1)">어려움<small>1일 후</small></button><button onclick="grade(2)">보통<small>간격 증가</small></button><button onclick="grade(3)">쉬움<small>간격 크게 증가</small></button></div><button class="btn master wide" onclick="masterFromStudy(${idx})">✓ 이 단어 완전 암기</button>`:`<button class="btn primary wide" onclick="S.answer=true;render()">정답 보기</button>`}`}
function grade(q){const a=queue();if(!a.length)return;const w=a[S.current],p=progress(),o=p[w.term]||{mastery:0},day=86400000;let m=o.mastery||0;if(q===0)p[w.term]={...o,mastered:false,mastery:Math.max(0,m-1),next:Date.now()+600000};if(q===1)p[w.term]={...o,mastered:false,mastery:Math.max(1,m),next:Date.now()+day};if(q===2){m=Math.min(5,m+1);p[w.term]={...o,mastered:false,mastery:m,next:Date.now()+[1,3,7,14,30,60][m]*day}}if(q===3){m=Math.min(5,m+2);p[w.term]={...o,mastered:false,mastery:m,next:Date.now()+[3,7,14,30,60,90][m]*day}}save(p);S.answer=false;S.current=Math.min(S.current,Math.max(0,queue().length-1));render()}
function masterFromStudy(i){const w=WORDS[i],p=progress(),o=p[w.term]||{mastery:0};p[w.term]={...o,mastered:true,next:null,masteredAt:Date.now()};save(p);S.answer=false;S.current=Math.min(S.current,Math.max(0,queue().length-1));render()}
function papers(){const m={};WORDS.forEach(w=>(m[w.paper]??=[]).push(w));return `<div class="paper-list">${Object.entries(m).sort().map(([p,a])=>`<div class="card paper-card"><strong>${p}</strong><div class="meta">연결된 단어 ${a.length}개</div></div>`).join('')}</div>`}
function settings(){return `<div class="card"><div class="setting"><strong>완전 암기</strong><p class="meta">완전 암기로 표시한 단어는 복습에서 자동 제외됩니다. 단어장 → 암기 완료에서 언제든 다시 복습에 넣을 수 있습니다.</p></div><div class="setting"><strong>발음</strong><p class="meta">IPA 아래에 한글 발음을 함께 표시하며, iPhone 기본 영어 TTS로 실제 발음을 들을 수 있습니다.</p></div><div class="setting"><strong>추가 요금 없음</strong><p class="meta">외부 AI API와 유료 서버를 사용하지 않습니다.</p></div><div class="setting"><strong>데이터 저장</strong><p class="meta">복습 기록과 즐겨찾기는 이 기기의 브라우저 저장소에 보관됩니다.</p></div></div>`}
function render(){V.innerHTML=S.tab==='home'?home():S.tab==='words'?wordsView():S.tab==='study'?study():S.tab==='papers'?papers():settings()}
document.querySelectorAll('.tabbar button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
