/* Scale/readability fixes loaded after app.js */
S.wordLimit=100;S.customSentence=null;
applyTheme=function(){const t=settings().theme;if(t==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.dataset.theme=t};applyTheme();
const _startMode=startMode;startMode=function(m){if(m==='sentence')S.customSentence=null;_startMode(m)};
const _readPaper=readPaper;readPaper=function(id){S.customSentence=null;_readPaper(id)};
readThisExample=function(i){S.readingPaper=null;S.customSentence={text:WORDS[i].example,translation:WORDS[i].translation,source:WORDS[i].paper,term:WORDS[i].term,sourceType:WORDS[i].sourceType};S.studyMode='sentence';S.sentenceIndex=0;S.sentenceReveal=false;S.sentenceChunks=false;setTab('study')};
const _baseSentencePool=sentencePool;sentencePool=function(){if(S.customSentence)return [S.customSentence];return _baseSentencePool()};
const _baseSentenceStudy=sentenceStudy;sentenceStudy=function(){const body=_baseSentenceStudy();return S.customSentence?`<div class="filter-banner"><span>선택한 예문만 독해 중</span><button onclick="S.customSentence=null;S.sentenceIndex=0;S.sentenceReveal=false;render()">전체 문장</button></div>${body}`:body};
function savedSentenceObjects(){const saved=new Set(difficult()),out=[];for(const p of (PAPER_LIBRARY||[]))for(const q of (p.passages||[]))if(saved.has(q.text))out.push({text:q.text,translation:q.translation,source:p.title});for(const w of WORDS)if(saved.has(w.example)&&!out.some(x=>x.text===w.example))out.push({text:w.example,translation:w.translation,source:w.paper});for(const t of saved)if(!out.some(x=>x.text===t))out.push({text:t,translation:'',source:''});return out}
function savedSentenceStudy(){const a=savedSentenceObjects();if(!a.length)return '<div class="empty card"><div class="done-icon">☆</div><h2>저장한 문장 없음</h2><p>문장 독해에서 별표를 누르면 어려운 문장을 여기에 모을 수 있습니다.</p></div>';return `<div class="section-title">저장한 어려운 문장 ${a.length}개</div>${a.map((x,i)=>`<div class="card saved-sentence"><div class="row between"><span class="source-mini">${escapeHtml(x.source)}</span><button class="icon-btn mini-icon" onclick="toggleDifficult(${JSON.stringify(x.text)})">★</button></div><p>${escapeHtml(x.text)}</p><div class="reading-tools"><button class="btn outline small" onclick="speak(${JSON.stringify(x.text)})">🔊 듣기</button><button class="btn secondary small" onclick="openSavedSentence(${i})">독해하기</button></div>${x.translation?`<div class="translation">${escapeHtml(x.translation)}</div>`:''}</div>`).join('')}`}
function openSavedSentence(i){const x=savedSentenceObjects()[i];if(!x)return;S.customSentence={...x,sourceType:'저장 문장'};S.studyMode='sentence';S.sentenceIndex=0;S.sentenceReveal=false;S.sentenceChunks=false;render()}
studyTabs=function(){return `<div class="study-tabs five"><button class="${S.studyMode==='review'?'active':''}" onclick="S.studyMode='review';S.answer=false;render()">단어</button><button class="${S.studyMode==='sentence'?'active':''}" onclick="S.customSentence=null;S.studyMode='sentence';S.sentenceReveal=false;render()">독해</button><button class="${S.studyMode==='cloze'?'active':''}" onclick="S.studyMode='cloze';S.clozeReveal=false;render()">빈칸</button><button class="${S.studyMode==='weak'?'active':''}" onclick="S.studyMode='weak';render()">약한 단어</button><button class="${S.studyMode==='saved'?'active':''}" onclick="S.studyMode='saved';render()">저장 문장</button></div>`};
study=function(){return studyTabs()+(S.studyMode==='review'?reviewStudy():S.studyMode==='sentence'?sentenceStudy():S.studyMode==='cloze'?clozeStudy():S.studyMode==='saved'?savedSentenceStudy():weakStudy())};
wordsView=function(){if(S.selected!==null)return detail(S.selected);const q=norm(S.search),p=progress(),f=fav(),base=S.paperFilter?paperWords(S.paperFilter):WORDS;let list=base.map(w=>({w,i:WORDS.indexOf(w)})).filter(({w})=>{const categoryOK=S.category==='전체'||w.category===S.category;const text=norm([w.term,w.korean,w.koreanPronunciation,w.meaning,w.example,w.translation,w.paper,...w.collocations].join(' '));const searchOK=!q||text.includes(q);const statusOK=S.mode==='all'||(S.mode==='fav'&&f.includes(w.term))||(S.mode==='mastered'&&p[w.term]?.mastered)||(S.mode==='weak'&&(p[w.term]?.wrong||0)>0&&!p[w.term]?.mastered);return categoryOK&&searchOK&&statusOK});if(S.sort==='alpha')list.sort((a,b)=>a.w.term.localeCompare(b.w.term));if(S.sort==='weak')list.sort((a,b)=>weakScore(b.w)-weakScore(a.w));if(S.sort==='priority')list.sort((a,b)=>(a.w.priority||3)-(b.w.priority||3)||a.w.term.localeCompare(b.w.term));const total=list.length,shown=list.slice(0,S.wordLimit),paperTitle=S.paperFilter?(PAPER_LIBRARY.find(x=>x.id===S.paperFilter)?.title||'논문 필터'):'';return `${paperTitle?`<div class="filter-banner"><span>논문 필터: ${escapeHtml(paperTitle)}</span><button onclick="S.paperFilter=null;S.wordLimit=100;render()">해제</button></div>`:''}<div class="search-row"><input class="search" placeholder="단어·뜻·예문·논문 검색" value="${escapeHtml(S.search)}" oninput="S.search=this.value;S.wordLimit=100;render()"><select onchange="S.sort=this.value;render()"><option value="priority" ${S.sort==='priority'?'selected':''}>추천순</option><option value="alpha" ${S.sort==='alpha'?'selected':''}>ABC순</option><option value="weak" ${S.sort==='weak'?'selected':''}>약한순</option></select></div><div class="status-tabs"><button class="${S.mode==='all'?'active':''}" onclick="S.mode='all';S.wordLimit=100;render()">전체</button><button class="${S.mode==='weak'?'active':''}" onclick="S.mode='weak';S.wordLimit=100;render()">△ 약한 단어</button><button class="${S.mode==='fav'?'active':''}" onclick="S.mode='fav';S.wordLimit=100;render()">★ 즐겨찾기</button><button class="${S.mode==='mastered'?'active':''}" onclick="S.mode='mastered';S.wordLimit=100;render()">✓ 암기 완료</button></div><div class="chips">${cats().map(c=>`<button class="chip ${c===S.category?'active':''}" onclick="S.category='${escapeHtml(c)}';S.wordLimit=100;render()">${escapeHtml(c)}</button>`).join('')}</div><div class="list-count">${total}개 중 ${Math.min(total,S.wordLimit)}개 표시</div><div>${shown.map(({w,i})=>wordCard(w,i,p,f)).join('')||'<div class="empty card">조건에 맞는 단어가 없습니다.</div>'}</div>${total>S.wordLimit?`<button class="btn secondary wide" onclick="S.wordLimit+=100;render()">100개 더 보기 (${total-S.wordLimit}개 남음)</button>`:''}`};
render();